# Generated by Django 4.0.4 on 2022-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersproposal', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
